### ISSUE TITLE
关于FLV录制问题

### ISSUE THREAD

**Issue by AsunaKazuto** [CHKZL/DDTV#168]
在采用FLV模式进行直播录制时，可能出现直播已开始但直播下载速度为0的情况。
在直播过程中，主播由于某些情况重新进行直播推流后，出现的可能性较大。

**Comment by CHKZL** [comment]
对应的日志文件还能找到么？看能不能提供一下日志文件让我方便分析原因日志文件在DDTV根目录下的log文件夹下，文件名是DDTV的启动时间。

**Comment by AsunaKazuto** [comment]
> 对应的日志文件还能找到么？看能不能提供一下日志文件让我方便分析原因日志文件在DDTV根目录下的log文件夹下，文件名是DDTV的启动时间。



> 对应的日志文件还能找到么？看能不能提供一下日志文件让我方便分析原因日志文件在DDTV根目录下的log文件夹下，文件名是DDTV的启动时间。

https://github.com/CHKZL/DDTV/issues/168#issuecomment-1556206201

**Comment by AsunaKazuto** [comment]
> 对应的日志文件还能找到么？看能不能提供一下日志文件让我方便分析原因日志文件在DDTV根目录下的log文件夹下，文件名是DDTV的启动时间。

2023/06/01 18:36:40:[Error][Post][477279260]Post请求发生网络层错误:UnknownError(16)[https://api.live.bilibili.com/room/v1/Room/get_status_info_by_uids] ,详细信息已写入txt文本日志中错误堆栈

System.Net.WebException: The SSL connection could not be established, see inner exception.

 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

 ---> System.IO.IOException: Unable to read data from the transport connection: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.

 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

   --- End of inner exception stack trace ---

   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)

   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)

   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)

   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)

   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)

   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)

   --- End of inner exception stack trace ---

   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)

   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)

   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)

   at System.Net.HttpWebRequest.SendRequest(Boolean async)

   at System.Net.HttpWebRequest.GetResponse()

   --- End of inner exception stack trace ---

   at System.Net.HttpWebRequest.GetResponse()

   at DDTV_Core.SystemAssembly.NetworkRequestModule.Post.Post.SendRequest_GetWebInfo_JsonClass(String url, String jsonParam, String encode)



2023/06/01 21:49:03:[Error][Post][488821659]Post请求发生网络层错误:UnknownError(16)[https://api.live.bilibili.com/room/v1/Room/get_status_info_by_uids] ,详细信息已写入txt文本日志中错误堆栈

System.Net.WebException: The SSL connection could not be established, see inner exception.

 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

 ---> System.IO.IOException: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.

 ---> System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。

   --- End of inner exception stack trace ---

   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)

   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)

   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)

   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)

   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)

   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)

   --- End of inner exception stack trace ---

   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)

   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)

   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)

   at System.Net.HttpWebRequest.SendRequest(Boolean async)

   at System.Net.HttpWebRequest.GetResponse()

   --- End of inner exception stack trace ---

   at System.Net.HttpWebRequest.GetResponse()

   at DDTV_Core.SystemAssembly.NetworkRequestModule.Post.Post.SendRequest_GetWebInfo_JsonClass(String url, String jsonParam, String encode)



2023/06/01 21:49:13:[Error][Post][488831666]Post请求发生网络层错误:UnknownError(16)[https://api.live.bilibili.com/room/v1/Room/get_status_info_by_uids] ,详细信息已写入txt文本日志中错误堆栈

System.Net.WebException: The SSL connection could not be established, see inner exception.

 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

 ---> System.IO.IOException: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.

 ---> System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。

   --- End of inner exception stack trace ---

   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)

   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)

   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)

   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)

   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)

   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)

   --- End of inner exception stack trace ---

   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)

   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)

   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)

   at System.Net.HttpWebRequest.SendRequest(Boolean async)

   at System.Net.HttpWebRequest.GetResponse()

   --- End of inner exception stack trace ---

   at System.Net.HttpWebRequest.GetResponse()

   at DDTV_Core.SystemAssembly.NetworkRequestModule.Post.Post.SendRequest_GetWebInfo_JsonClass(String url, String jsonParam, String encode)



2023/06/01 21:53:47:[Error][DownloadClass][489105463]新建下载任务发生意料外的错误 ,详细信息已写入txt文本日志中错误堆栈

System.IO.IOException: Unable to read data from the transport connection: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.

 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)

   --- End of inner exception stack trace ---

   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)

   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)

   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)

   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)

   at System.IO.Stream.Read(Span`1 buffer)

   at System.Net.Http.HttpConnection.Read(Span`1 destination)

   at System.Net.Http.HttpConnection.ConnectionCloseReadStream.Read(Span`1 buffer)

   at System.Net.Http.HttpBaseStream.ReadByte()

   at DDTV_Core.SystemAssembly.DownloadModule.DownloadClass.Downloads.<>c__DisplayClass119_0.<<DownFLV_HttpWebRequest>b__0>d.MoveNext()

**Comment by AsunaKazuto** [comment]
> > 对应的日志文件还能找到么？看能不能提供一下日志文件让我方便分析原因日志文件在DDTV根目录下的log文件夹下，文件名是DDTV的启动时间。
> 
> 2023/06/01 18:36:40:[Error][Post][477279260]Post请求发生网络层错误:UnknownError(16)[https://api.live.bilibili.com/room/v1/Room/get_status_info_by_uids] ,详细信息已写入txt文本日志中错误堆栈
> 
> System.Net.WebException: The SSL connection could not be established, see inner exception.
> 
> ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
> 
> ---> System.IO.IOException: Unable to read data from the transport connection: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
> 
> ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
> 
> --- End of inner exception stack trace ---
> 
> at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
> 
> at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
> 
> at System.Net.Security.SslStream.g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
> 
> at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
> 
> at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
> 
> at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
> 
> --- End of inner exception stack trace ---
> 
> at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
> 
> at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
> 
> at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> 
> at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
> 
> at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
> 
> at System.Net.HttpWebRequest.SendRequest(Boolean async)
> 
> at System.Net.HttpWebRequest.GetResponse()
> 
> --- End of inner exception stack trace ---
> 
> at System.Net.HttpWebRequest.GetResponse()
> 
> at DDTV_Core.SystemAssembly.NetworkRequestModule.Post.Post.SendRequest_GetWebInfo_JsonClass(String url, String jsonParam, String encode)
> 
> 2023/06/01 21:49:03:[Error][Post][488821659]Post请求发生网络层错误:UnknownError(16)[https://api.live.bilibili.com/room/v1/Room/get_status_info_by_uids] ,详细信息已写入txt文本日志中错误堆栈
> 
> System.Net.WebException: The SSL connection could not be established, see inner exception.
> 
> ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
> 
> ---> System.IO.IOException: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
> 
> ---> System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
> 
> --- End of inner exception stack trace ---
> 
> at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
> 
> at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
> 
> at System.Net.Security.SslStream.g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
> 
> at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
> 
> at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
> 
> at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
> 
> --- End of inner exception stack trace ---
> 
> at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
> 
> at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
> 
> at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> 
> at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
> 
> at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
> 
> at System.Net.HttpWebRequest.SendRequest(Boolean async)
> 
> at System.Net.HttpWebRequest.GetResponse()
> 
> --- End of inner exception stack trace ---
> 
> at System.Net.HttpWebRequest.GetResponse()
> 
> at DDTV_Core.SystemAssembly.NetworkRequestModule.Post.Post.SendRequest_GetWebInfo_JsonClass(String url, String jsonParam, String encode)
> 
> 2023/06/01 21:49:13:[Error][Post][488831666]Post请求发生网络层错误:UnknownError(16)[https://api.live.bilibili.com/room/v1/Room/get_status_info_by_uids] ,详细信息已写入txt文本日志中错误堆栈
> 
> System.Net.WebException: The SSL connection could not be established, see inner exception.
> 
> ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
> 
> ---> System.IO.IOException: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
> 
> ---> System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
> 
> --- End of inner exception stack trace ---
> 
> at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
> 
> at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
> 
> at System.Net.Security.SslStream.g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
> 
> at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
> 
> at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
> 
> at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
> 
> --- End of inner exception stack trace ---
> 
> at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
> 
> at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
> 
> at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> 
> at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
> 
> at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
> 
> at System.Net.HttpWebRequest.SendRequest(Boolean async)
> 
> at System.Net.HttpWebRequest.GetResponse()
> 
> --- End of inner exception stack trace ---
> 
> at System.Net.HttpWebRequest.GetResponse()
> 
> at DDTV_Core.SystemAssembly.NetworkRequestModule.Post.Post.SendRequest_GetWebInfo_JsonClass(String url, String jsonParam, String encode)
> 
> 2023/06/01 21:53:47:[Error][DownloadClass][489105463]新建下载任务发生意料外的错误 ,详细信息已写入txt文本日志中错误堆栈
> 
> System.IO.IOException: Unable to read data from the transport connection: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
> 
> ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
> 
> at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
> 
> --- End of inner exception stack trace ---
> 
> at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
> 
> at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
> 
> at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
> 
> at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
> 
> at System.IO.Stream.Read(Span`1 buffer)
> 
> at System.Net.Http.HttpConnection.Read(Span`1 destination)
> 
> at System.Net.Http.HttpConnection.ConnectionCloseReadStream.Read(Span`1 buffer)
> 
> at System.Net.Http.HttpBaseStream.ReadByte()
> 
> at DDTV_Core.SystemAssembly.DownloadModule.DownloadClass.Downloads.<>c__DisplayClass119_0.<<DownFLV_HttpWebRequest>b__0>d.MoveNext()

当时的日志找不到了，只有之后发生类似情况的日志。

**Comment by CHKZL** [comment]
因为和最新的提问重复了，这个我就关闭了，到最新的里面统一回复
