### ISSUE TITLE
通过浏览器访问/file目录，在终端可见报错

### ISSUE THREAD

**Issue by Janet-Baker** [CHKZL/DDTV#28]
DDLIVE录制器在centos7.6上运行时，通过网页浏览器访问/file目录，在终端可见报错
```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://IP:11419/file
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint '/file HTTP: GET'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint '/file HTTP: GET'
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM1GKV9DQEQP", Request id "0HM1GKV9DQEQP:00000002": An unhandled exception was thrown by the application.
System.IO.DirectoryNotFoundException: Could not find a part of the path '/data/LiveREC/tmp'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.DirectoryInfo.GetDirectories(String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.DirectoryInfo.GetDirectories()
   at DDTVLiveRecWebServer.Startup.<>c.<<Configure>b__1_2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 1.5056ms 500
```
初步判断是没有妥善应对缺少相关文件的缺省措施（比如可以创建一个文件）。这个问题在首次启动时缺少`BiliUser.ini`时也有出现，甚至更为严重（缺少时，应用不能启动）。

此外，录制器[https://github.com/CHKZL/DDTV2/tree/master/DDTVLiveRec](https://github.com/CHKZL/DDTV2/tree/master/DDTVLiveRec)的README中，出现了明显的复制粘贴痕迹（没改完）：

> 这样的内容组成，其中
> ["RoomNumber"]为DDTV直播状态标识，在DDTVLive中无用，默认为false

**Comment by CHKZL** [comment]
感谢，已经修复了
访问file报错的问题之前一直没发现是因为只要第一个任务创建了就会自动检查目录的完整性，我在测试的时候一直都有人在播，所以没发现这个问题，现在修改为启动的时候就会检查tmp目录了

README中因为粗心出现复制修改错误的部分已经修改

至于缺少BiliUser.ini的问题我没有复现出来..至少我删除所有文件后启动也没有出现不能正确启动的问题，如果有办法复现无法启动的问题，可以描述一下复现过程么？

**Comment by CHKZL** [comment]
BiliUser.ini空白的问题可能是因为在不合适的地方使用了Task，我把检测BiliUser.ini和生成默认文件的方法放到主线程同步进行了，现在应该没问题了
